from .discogs import (
    DiscogsArtist,
    DiscogsCatalogHit,
    DiscogsProviderError,
    DiscogsRelease,
    DiscogsTrack,
    classify_release,
    fetch_catalog_release,
    fetch_label_releases,
    fetch_artist_releases as fetch_discogs_artist_releases,
    fetch_release_tracks as fetch_discogs_release_tracks,
    release_badges,
    search_artists as search_discogs_artists,
    search_catalog,
)
from .service import (
    ArtistCandidate,
    ArtistSearchResult,
    Edition,
    ReleaseGroup,
    Track,
    fetch_artist_release_groups,
    fetch_release_group_editions,
    fetch_release_tracklist,
    search_artists,
    search_artists_with_fallback,
)

__all__ = [
    "ArtistCandidate",
    "ArtistSearchResult",
    "DiscogsArtist",
    "DiscogsCatalogHit",
    "DiscogsProviderError",
    "DiscogsRelease",
    "DiscogsTrack",
    "Edition",
    "ReleaseGroup",
    "Track",
    "classify_release",
    "fetch_catalog_release",
    "fetch_label_releases",
    "fetch_artist_release_groups",
    "fetch_discogs_artist_releases",
    "fetch_discogs_release_tracks",
    "fetch_release_group_editions",
    "fetch_release_tracklist",
    "release_badges",
    "search_artists",
    "search_artists_with_fallback",
    "search_discogs_artists",
    "search_catalog",
    "ArtistRelation",
    "ArtistRelationsResponse",
    "ArtistSearchResponse",
    "CatalogSearchController",
    "MusicBrainzClient",
    "MusicBrainzClientError",
    "ReleaseGroupResponse",
    "RequestTrace",
    "default_client",
    "default_controller",
]


from .client import (
    MusicBrainzClient,
    MusicBrainzClientError,
    RequestTrace,
    default_client,
)
from .controller import (
    ArtistRelation,
    ArtistRelationsResponse,
    ArtistSearchResponse,
    CatalogSearchController,
    ReleaseGroupResponse,
    default_controller,
)
