from .discogs import (
    DiscogsArtist,
    DiscogsCatalogHit,
    DiscogsProviderError,
    DiscogsRelease,
    DiscogsTrack,
    classify_release,
    fetch_catalog_release,
    fetch_label_releases,
    fetch_artist_releases as fetch_discogs_artist_releases,
    fetch_release_tracks as fetch_discogs_release_tracks,
    release_badges,
    search_artists as search_discogs_artists,
    search_catalog,
)
from .service import (
    ArtistCandidate,
    Edition,
    ReleaseGroup,
    Track,
    fetch_artist_release_groups,
    fetch_release_group_editions,
    fetch_release_tracklist,
    search_artists,
)

__all__ = [
    "ArtistCandidate",
    "DiscogsArtist",
    "DiscogsCatalogHit",
    "DiscogsProviderError",
    "DiscogsRelease",
    "DiscogsTrack",
    "Edition",
    "ReleaseGroup",
    "Track",
    "classify_release",
    "fetch_catalog_release",
    "fetch_label_releases",
    "fetch_artist_release_groups",
    "fetch_discogs_artist_releases",
    "fetch_discogs_release_tracks",
    "fetch_release_group_editions",
    "fetch_release_tracklist",
    "release_badges",
    "search_artists",
    "search_discogs_artists",
    "search_catalog",
]
